name: dspace
channels:
  - conda-forge
dependencies:
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - python
  - python-dateutil
  - requests
  - seaborn
  - pyyaml
  - pip:
    - git+https://github.com/the-library-code/dspace-rest-python
